on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ['386', arm64, amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 'https://golang.org/dl/go1.15.8.linux-amd64.tar.gz'
          project_path: './cmd/abt'
          binary_name: 'abt'
