# on:
#   push:
#     branches:
#       - main
#     tags:
#       - v*
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ['386', arm64, amd64]
        exclude:
          - goarch: '386'
            goos: windows
          - goarch: '386'
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 'https://golang.org/dl/go1.15.8.linux-amd64.tar.gz'
          project_path: ./cmd/abt
          ldflags: -s -w
          build_flags: -a -installsuffix cgo
          binary_name: 'abt'
